/* eslint-disable */
// Generated by unplugin-auto-import
export {}
declare global {
  const SYSTEM_CMS: typeof import('./shared/systems').SYSTEM_CMS
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const dayjs: typeof import('dayjs')['default']
  const defineProps: typeof import('vue').defineProps
  const isUndefined: typeof import('@anzusystems/common-admin').isUndefined
  const onMounted: typeof import('vue').onMounted
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const unref: typeof import('vue').unref
  const useI18n: typeof import('vue-i18n').useI18n
  const watch: typeof import('vue').watch
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ComputedRef, Ref } from 'vue'
  import('vue')
  // @ts-ignore
  export type { DocId, IntegerId } from './types/ids'
  import('./types/ids')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
  }
}
