import { describe, expect, it } from 'vitest'
import { createMemoryHistory, createRouter, type RouteRecordRaw } from 'vue-router'
import { parseTypedRouterDeclaration } from '@/testing/typedRouter'

// One value per id shape the admins constrain a param to: an integer id, a uuid (any version, the
// backends make v4, v6 and v7) and a log's Mongo ObjectId.
const PARAM_SAMPLES = ['1', '00000000-0000-4000-8000-000000000001', '000000000000000000000001']

export interface DescribeGeneratedRoutesOptions {
  /** `routes` from `vue-router/auto-routes`. */
  routes: RouteRecordRaw[]
  /** `src/typed-router.d.ts`, imported with `?raw`. */
  declaration: string
  /** `Object.keys(import.meta.glob('/src/pages/**\/*.vue'))`. */
  pageFiles: string[]
  /** The catch-all's param, whose route is left out. */
  catchAll?: string
}

/**
 * A smoke test over every generated route.
 *
 * `anzu/valid-route-name` checks that a name referenced in the code exists. It cannot check that the
 * route behind it can be reached: a path whose constraint never matches, or one shadowed by an earlier
 * record, still has a perfectly valid name. Navigating to it lands on the catch-all instead, which
 * renders a 404 page and throws nothing -- so a broken route looks exactly like a working one until
 * somebody clicks it.
 *
 * Importing `vue-router/auto-routes` is itself half the test: it pulls in every page component and,
 * through them, their stores, api clients and composables, so anything that throws while a module is
 * evaluated fails there. That half depends on `importMode` being `sync` in the admin's vitest config.
 */
export function describeGeneratedRoutes({
  routes,
  declaration,
  pageFiles,
  catchAll = 'pathMatch',
}: DescribeGeneratedRoutesOptions): void {
  const declaredPaths = parseTypedRouterDeclaration(declaration).paths.filter(({ path }) => !path.includes(catchAll))
  const router = createRouter({ history: createMemoryHistory(), routes })

  // A constrained param -- `:id(\d+)`, a uuid, a log's ObjectId -- has to be filled with something its
  // regex accepts, or the route would fail to match for a reason that says nothing about the route
  // itself: the first sample the regex takes, else `sample`. The trailing `?` of an optional param
  // goes with it: left in place it starts a query string, and everything after it -- `/edit` in
  // `/articles/:docId/:version?/edit` -- stops being part of the path.
  const fillParams = (path: string) =>
    path.replace(/:[a-zA-Z]+(?:\(((?:\\.|[^\\)])*)\))?\??/g, (_match, regex?: string) =>
      regex
        ? // vue-router reads `\)` as a group's closing parenthesis inside a custom regex, `RegExp` would not.
          (PARAM_SAMPLES.find((sample) => new RegExp(`^(?:${regex.replace(/\\\)/g, ')')})$`, 'i').test(sample)) ??
          'sample')
        : 'sample'
    )

  describe('generated routes', () => {
    it('declares exactly the pages that exist on disk', () => {
      // A guard on the guard: if the declaration were missing or the regex stopped matching, every
      // assertion below would iterate an empty list and pass while checking nothing. Counted from
      // disk rather than against a literal, so it cannot go stale as pages are added or removed --
      // the one page file `declaredPaths` filters out is the catch-all.
      expect(declaredPaths.length).toBe(pageFiles.length - 1)
    })

    it.each(declaredPaths)('resolves $path to its own record, not the catch-all', ({ name, path }) => {
      const resolved = router.resolve(fillParams(path))

      expect(resolved.matched.some((record) => record.path.includes(catchAll))).toBe(false)
      expect(resolved.name).toBe(name)
    })

    it('has a runtime route for every declared one, and nothing extra', () => {
      // The declaration is generated from the same scan as `routes`, but they are two artifacts and
      // only one of them is regenerated by `generate:dts`. A stale declaration is exactly the state in
      // which the assertions above would check routes the app no longer has.
      //
      // `router.getRoutes()` rather than `routes`: nested pages are children, so the raw array holds
      // `/blogs/[id]` but not the `/blogs/[id]/edit` underneath it.
      //
      // Worth knowing when this fails locally and not in CI: a dev server left running watches
      // `src/pages` and rewrites the declaration the moment a page file changes, which hides the
      // mismatch this asserts. In CI nothing watches, and `generate:dts` runs before the tests.
      const runtime = new Set(
        router
          .getRoutes()
          .map((route) => route.name)
          .filter((name): name is string => typeof name === 'string')
      )
      const declared = new Set(declaredPaths.map(({ name }) => name))

      expect([...declared].filter((name) => !runtime.has(name))).toEqual([])
      expect([...runtime].filter((name) => !declared.has(name) && !name.includes(catchAll))).toEqual([])
    })

    it('gives every route a component to render', () => {
      const withoutComponent = router
        .getRoutes()
        .filter((route) => !route.components || Object.keys(route.components).length === 0)

      expect(withoutComponent.map((route) => route.path)).toEqual([])
    })
  })
}
