/* eslint-disable */
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue').computed
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const toRaw: typeof import('vue').toRaw
  const useStore: typeof import('./shared/store').useStore
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Flag } from './types/flag'
  import('./types/flag')
}
