name: 'CI'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        node-version:
          - '20'
        platform:
          - ubuntu-latest

    name: Lint
    runs-on: ${{ matrix.platform }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Yarn CI
        run: yarn ci

      - name: Run Security check
        run: yarn npm audit
