# Created by release-tools init: releases are made with release:start and release:publish, never by hand.
name: Release
on:
  push:
    tags: ['[0-9]*.[0-9]*.[0-9]*']
concurrency:
  group: release
  cancel-in-progress: false
  queue: max
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
  build:
    if: ${{ !github.event.deleted }}
    runs-on: ubuntu-latest
    permissions: { contents: read, actions: read, pull-requests: read }
    outputs:
      release: ${{ steps.build.outputs.release }}
      tag-object: ${{ steps.build.outputs.tag-object }}
      tarball-sha512: ${{ steps.build.outputs.tarball-sha512 }}
    steps:
      - id: build
        uses: anzusystems/release-tools/publish@main
        with: { mode: build }
  publish:
    needs: build
    if: needs.build.outputs.release == 'true'
    runs-on: ubuntu-latest
    environment: npmjs-publish
    permissions: { contents: write, id-token: write }
    outputs:
      version: ${{ steps.publish.outputs.version }}
      tag: ${{ steps.publish.outputs.tag }}
      prerelease: ${{ steps.publish.outputs.prerelease }}
      latest: ${{ steps.publish.outputs.latest }}
      published: ${{ steps.publish.outputs.published }}
      released-now: ${{ steps.publish.outputs.released-now }}
    steps:
      - id: publish
        uses: anzusystems/release-tools/publish@main
        with:
          mode: publish
          tag-object: '${{ needs.build.outputs.tag-object }}'
          tarball-sha512: '${{ needs.build.outputs.tarball-sha512 }}'
